name: Ubuntu with systemd in Docker
on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'
      - 'docker-entrypoint.sh'
      - '/etc/systemd/journald.conf'
      - 'systemd.json'
      - '.github/workflows/main.yml'

jobs:
  systemd:
    runs-on: [ubuntu-latest]
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build local/systemd - this adds STOPSIGNAL and is used as a base for packer
        run: |
          docker build \
            -f Dockerfile \
            --build-arg=DOCKER_FROM="ubuntu:focal" \
            -t local/systemd:focal \
            .
          docker build \
           -f Dockerfile \
           --build-arg=DOCKER_FROM="ubuntu:bionic" \
           -t local/systemd:bionic \
           .
          docker build \
            -f Dockerfile \
            --build-arg=DOCKER_FROM="ubuntu:xenial" \
            -t local/systemd:xenial \
            .
          docker build \
            -f Dockerfile \
            --build-arg=DOCKER_FROM="centos:centos8" \
            -t local/systemd:centos8 \
            .
          docker build \
            -f Dockerfile \
            --build-arg=DOCKER_FROM="centos:centos7" \
            -t local/systemd:centos7 \
            .
      - name: Build and push systemd with packer
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          packer build \
            --var=BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
            --var=VCS_REF="$(git rev-parse --verify HEAD | cut -c1-8)" \
            systemd.json
